GlobalPlanner:
  allow_unknown: false #true
  default_tolerance: 0.0
  visualize_potential: false
  use_dijkstra: true #if true,use dijkstra's algorithm
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false