local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  transform_tolerance: 2.0 #default:0.2

   #Rate parameters
  update_frequency: 5.0 #default:5.0
  public_frequency: 5.0 #default:0.0

  #map params
  static_map: false #default:false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

  inscribed_radius: 0.22 #default:0.325
  circumscribed_radius: 0.22
  
  plugins:
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: local_inflation_layer, type: "costmap_2d::InflationLayer"}